---
# This Ansible playbook triggers the role that we desire

- hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
    - name: Install Spark Master
      include_role:
        name: spark-master-2
