
configurations:
- varconfig.yaml

resources:
- ../../resource/calico/
- ../../resource/cluster-autoscaler/
- ../../resource/event-router/
- ../../resource/ingress/
- ../../resource/instana/
- ../../resource/mongo/
- ../../resource/route53/
- ../../resource/splunk/
- ../../resource/pax-operator/
- ../../resource/overprovisioner/

vars:
  - name: MONGO-REPLICA-COUNT
# This is not used by Pax-Operator so use - not _
    objref:
      kind: ConfigMap
      name: pax-operator-env
      namespace: pax-operator
      apiVersion: v1
    fieldref:
      fieldpath: data.MONGO-REPLICA-COUNT
  - name: MONGO-PASSWORD
    objref:
      kind: ConfigMap
      name: pax-operator-env
      namespace: pax-operator
      apiVersion: v1
    fieldref:
      fieldpath: data.MONGO_PASSWORD
  - name: MONGO-USERNAME
    objref:
      kind: ConfigMap
      name: pax-operator-env
      namespace: pax-operator
      apiVersion: v1
    fieldref:
      fieldpath: data.MONGO_USERNAME
