apiVersion: paxata.com/v1
kind: PaxInstallation
metadata:
  name: pax-installation
spec:
  paxserver:
    applicationProperties:
      guardrail.project.row.limit: "1500000"
      guardrail.batch.row.limit: "10000000"
      guardrail.interactive.buffer.limit: "1500000"
      guardrail.file.size.limit: "5000000"
      guardrail.interactive.row.warning: "10000000"
      guardrail.library.row.limit: "5000000"
      guardrail.px.pipeline.inactivity.timeout: "10"
      guardrail.px.pipeline.executors: "2"
    numCpus: 5
    memoryMB: 12288
  pipelineProxy:
    applicationProperties:
      px_pps_spark_conf_spark_driver_memory: "8g"
      px_pps_spark_conf_spark_driver_cores: "2"
      px_pps_spark_conf_spark_driver_extraJavaOptions: "-XX:+UseG1GC -XX:+UseCompressedOops -XX:-OmitStackTraceInFastThrow -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -Dpx.total.cache.capacity=1000000"
      px_pps_spark_conf_spark_executor_cores: "4"
      px_pps_spark_conf_spark_executor_memory: "16g"
      px_pps_spark_conf_spark_executor_extraJavaOptions: "-XX:+UseCompressedOops -XX:-OmitStackTraceInFastThrow -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m"
