- name: Validate
  assert:
      that:
        - "source_rpm != '' "
      msg: Please define source_rpm in the group vars

- name: Download {{ source_rpm }} from S3
  aws_s3:
    mode: get
    bucket: "{{ paxata_file_repo_s3 }}"
    object: /files/{{ java_rpm }}
    dest: /tmp/{{ java_rpm }}
    aws_access_key: "{{pfr_aws_access_key}}"
    aws_secret_key: "{{pfr_aws_secret_key}}"
    overwrite: false # Prevent RE-download during testing


- name: Install {{ source_rpm }}
  yum:
    name: /tmp/{{java_rpm}}
    state: present
