---

- name:  Set the host name as specified in the User Data
  hostname:
    name: "{{host_name}}"

- name:  Update the network sysconfig
  lineinfile:
    path: /etc/sysconfig/network
    regexp: '^[#]?HOSTNAME=.*$'
    line: "HOSTNAME={{host_name}}"

- name: Add Preserve Hostname True to cloud config
  lineinfile:
    path: "/etc/cloud/cloud.cfg"
    line: 'preserve_hostname: true'
