---

- name: Move and overwrite JARs in the java installation
  copy:
    src: "{{ item }}"
    dest: "{{ real_java_path }}/../../lib/security/{{ item }}"
    force: true
    backup: true
  with_items:
      - local_policy.jar
      - README.txt
      - US_export_policy.jar
