
# Add in additional env vars

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: splunk-kubernetes-metrics-agg
spec:
  template:
    spec:
      containers:
      - name: splunk-fluentd-k8s-metrics-agg
        env:
        - name: SPLUNK_HEC_HOST
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-metrics
              key: splunk_hec_host
