---
- name: Create Terraform directory
  file:
    path: "{{terraform_dir}}"
    state: directory
    owner: "{{devops_user}}"
    group: "{{devops_user}}"
  register: terraform_directory

- name: Check terraform version
  shell: "terraform --version 2>&1 | grep {{terraform_version}}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- include: download.yml
  when: terraform_versions_match.rc != 0

- name: Install unzip to unarchive terraform
  yum:
    name: unzip
    state: present

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "{{terraform_dir}}"
    copy: no
  when: terraform_versions_match.rc != 0 or terraform_directory.changed

- name: Make devops_user terraform directory owner
  file:
    path: "{{terraform_dir}}"
    state: directory
    owner: "{{devops_user}}"
    group: "{{devops_user}}"
    recurse: yes

- name: Adding terraform command to user path
  file:
    src: "{{terraform_dir}}/terraform"
    dest: /usr/bin/terraform
    state: link
