

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: xfs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
