---

- hosts: all
  become: yes
  tasks:

    - name: Parse the User Data into Facts
      include_role:
        name: load-user-data

    - name: Set the Instana API Key
      include_role:
        name: setup-instana
