
# Add in additional env vars

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-logging
spec:
  template:
    spec:
      containers:
      - name: splunk-fluentd-k8s-logs
        env:
        - name: SPLUNK_HEC_HOST
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-logging
              key: splunk_hec_host
