# this part downloaded from: https://raw.githubusercontent.com/GoogleCloudPlatform/metacontroller/master/manifests/metacontroller-rbac.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: metacontroller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metacontroller
  namespace: metacontroller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metacontroller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metacontroller
subjects:
- kind: ServiceAccount
  name: metacontroller
  namespace: metacontroller
roleRef:
  kind: ClusterRole
  name: metacontroller
  apiGroup: rbac.authorization.k8s.io

---

# this part downloaded from: https://raw.githubusercontent.com/GoogleCloudPlatform/metacontroller/master/manifests/metacontroller.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositecontrollers.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: compositecontrollers
    singular: compositecontroller
    kind: CompositeController
    shortNames:
    - cc
    - cctl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decoratorcontrollers.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: decoratorcontrollers
    singular: decoratorcontroller
    kind: DecoratorController
    shortNames:
    - dec
    - decorators
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: controllerrevisions
    singular: controllerrevision
    kind: ControllerRevision
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metacontroller
  namespace: metacontroller
  labels:
    app: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metacontroller
  serviceName: ""
  template:
    metadata:
      labels:
        app: metacontroller
    spec:
      serviceAccountName: metacontroller
      containers:
      - name: metacontroller
        image: metacontroller/metacontroller:v0.4.0
        command: ["/usr/bin/metacontroller"]
        args:
        - --logtostderr
        - -v=5
        - --discovery-interval=20s
  volumeClaimTemplates: []
