# This is the main object that describes a Paxata installation and all the variables that go into one.
# The required fields on this object are the minimum set of what's required in order to create a full
# Paxata instance, which at the moment includes paxserver, pipeline-proxy.
# You can get/apply/patch/delete resources of this type, and metacontroller and pax-installation-controller
# will conspire to create the installation for you.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: paxinstallations.paxata.com
spec:
  group: paxata.com
  names:
    kind: PaxInstallation
    listKind: PaxInstallationList
    plural: paxinstallations
    singular: paxinstallation
    shortNames:
      - pax
    categories:
      - all
  scope: Namespaced
  versions:
    - name: v1
      storage: true
      served: true
    - name: v1beta1
      served: true
      storage: false
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Active
      type: boolean
      description: The desired state of whether the installation should be running or not
      JSONPath: .spec.active
    - name: Running
      type: boolean
      description: Whether the installation is currently running and ready
      JSONPath: .status.current.allRunning
    - name: Last Status Update
      type: date
      description: Timestamp of the last status update
      JSONPath: .status.current.time
    - name: Pax Server Version
      type: string
      description: Version of the paxserver image
      JSONPath: .spec.paxserver.imageVersion
    - name: Pod Statuses
      type: string
      description: Summary of pod statuses
      JSONPath: .status.current.podStatuses
    - name: URL
      type: string
      description: Paxserver http URL
      JSONPath: .status.paxserverUrl
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - active
            - paxserver
            - pipelineProxy
            - libraryStorage
            - pesKeySecretName
          properties:
            active:
              type: boolean
              description: |-
                The desired state of the installation, whether it should be running or not. If
                active is false, then the installation will be shut down immediately. If active is
                true, then the operator will attempt to start it.
            pesKeySecretName:
              type: string
              description: |-
                The name of a kubernetes Secret in the same namespace that contains the content of the pes.properties file for paxserver.
                The controller does not generate pes keys automatically, but expects that one has already been created for each installation.
            libraryStorage:
              oneOf:
                - type: object
                  required:
                    - type
                  properties:
                    type:
                      enum: [ "local" ]
                - type: object
                  required:
                    - type
                    - coreSiteSecretName
                    - rootPath
                  properties:
                    type:
                      enum: [ "s3" ]
                    coreSiteSecretName:
                      type: string
                    rootPath:
                      type: string
            paxserver:
              type: object
              required:
                - imageName
                - imageVersion
                - numCpus
                - memoryMB
              properties:
                imageName:
                  type: string
                imageVersion:
                  type: string
                numCpus:
                  type: number
                memoryMB:
                  type: integer
                applicationProperties:
                  type: object
                  additionalProperties: true
                jvmArgs:
                  type: array
                  items:
                    type: string
            pipelineProxy:
              type: object
              required:
                - imageName
                - imageVersion
                - numCpus
                - memoryMB
              properties:
                imageName:
                  type: string
                imageVersion:
                  type: string
                numCpus:
                  type: number
                memoryMB:
                  type: integer
                applicationProperties:
                  type: object
                  additionalProperties: true
                jvmArgs:
                  type: array
                  items:
                    type: string
            mongo:
              type: object
              properties:
                databaseName:
                  type: string
                  description: Deprecated, will be removed in a future version
                credentialSecretName:
                  type: string
                  description: |-
                    The name of a Kubernetes Secret that contains credentials for connecting to MongoDB. The secret
                    must contain the following fields: MONGO_HOSTS, MONGO_USERNAME, MONGO_PASSWORD, MONGO_DB_NAME, MONGO_URI.
                    This field allows you to opt out of automatic database management.
