---

apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: overprovisioning
value: -1
globalDefault: false
description: "Priority class used by overprovisioning."

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-overprovisioning
spec:
  replicas: 19
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline-overprovisioning
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipeline-overprovisioning
    spec:
      nodeSelector:
        paxata.com/role-id: spark-server
      priorityClassName: overprovisioning
      containers:
      - name: reserve-resources
        image: k8s.gcr.io/pause
        resources:
          requests:
            cpu: "7"
