
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#URL not supported yet; https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/calico.yaml
  - calico.yaml
