---

- hosts: all
  become: yes
  tasks:

    - name: Parse the User Data into Facts
      include_role:
        name: load-user-data

    - name: Set the SSH Certificate
      include_role:
        name: setup-ssh
