- name: disabled selinux
  selinux: state=disabled
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'
  
- name: disabled selinux
  selinux: state=permissive policy=targeted
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
