---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: ../../roles
  require_chef_for_busser: false
  require_ansible_omnibus: false
  require_ansible_repo: false
  ansible_verbose: true
  ansible_verbosity: 4

platforms:
  - name: yum-plugin-s3
    driver_plugin: vagrant
    driver_config:
      box: paxata/server-base
suites:
  - name: default
