
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage-mongo-deployment-0
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 60Gi
  storageClassName: mongo-storage-class
  volumeName: mongo-volume-0
