
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume-0
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: $(MONGO-VOLUME-ID)
  capacity:
    storage: 60Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-storage-class
