apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- varconfig.yaml

resources:
- mongo.yaml
- stateful-set.yaml
- service.yaml
- network-policy.yaml

configMapGenerator:
- name: mongo-init-script
  namespace: mongo
  files:
  - init-mongo.sh
