apiVersion: v1
kind: Namespace
metadata:
  name: mongo

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-certificates
  namespace: mongo
type: Opaque
data:
  keyfile: TmU3YXh1WG9EaXJmZ1RWUkZEUTZLZ2p0ZEdlZjlTbGtoOFg2dWJtSWFTM0M0TGhPbm1xUTlhNEU4bm5FUDJMTApuWlZZL0hhbHBuWkh0K0IvWkZzSStFREh0dThBR2EzZHpRUEh6YXFjcENmWUhzS3pZcXpQbmxIaWpMWUpCYzdECmNVK2dyMlpNU0dDTkNqcXZ3TlBMWC9OdnBkOVQvYjZvdlQ5bGd5Mmp3VDhWZ1RIRUI0My92WHFjL0c5ZktzdU0KNlJSWjBXR1crb1VvRjZYdjVFN0lRWDNFNlV2WWVzN3d5UkxXUm92N2ZaNVZnaW5pcENqbkFKdWVNNEhuOTBGOApxOFFod09TUzg0RkdLdzBGLzNxY0Qwd05Zb2VsMVI0bjJWbEhjUTlnQTNvL0RBOTA1bFc3dWFmTEFUbmljMXFuClUwU2hhNHVMWTVOZmE1L2huVXBrNUZ4ZDNLTmxvSVovQ0VJdmJsYWpQYmdaaGxDYWxtbUhBOGJhY3d5U1JXeVIKeWNHMmpERmM0UjlINGpTcDZIQjZQNVpiWmQ3QjlDeU1YMzVud2tRcWJGU2tPMFIybGZrYnNIOXVBWVdNOGltbApWVXlxSFR5aHhGT3luTXlrYjVBSGZscFlvMGtwanNFc1ZOUlBveGtaZkxrVHFISkp4WEh2VnVVVW9wUHN5d1gwCjlLamw4Ny93a1hudnNSWksyMTBDVFJIcVJkTU0wZEJGV2lRUWtXOFNYMHZvaDUrdGZUZmE0NU9QQmdmU2FEVVAKYlM2UGF3NDlLTXNjcm1Ka2pCZkdSeExvb0lNYk1TTmJPdzdkZlNSUENKYW9aSmlXRW52d1Axb21lNGRydUtiSQpDbXlYSVArYWpYVVJyZGpSV0NEZ1lKRzFWRTdJY0xOVjErR0xSbU51blB3aDRhb0JXeFhVVEtTRS84aElKZWMwCnVJUlExdk1nd2ExZSt3VnpVNU1TMldBQUcxUnU4bVEwODd2aVRmQW9ic3k0RjNxS2FzNXk3Q3hjWWk5YTk5ZVgKc1psZCs5MUwvR3hGOFRPTDNrNTY2VE1nYUg1am9zRDJMNUVYT0FRNVZDekhGTVZFc0Z1cnlrWmNQYXNhSGZUbwp2RUtFT1c5VW9DMUE1T3NsYVp6UHFTRmFtUnhYMkNwMTlaQVNZOW1JcERZUmowTnpJWFVCSTBhRjFNa3RmWjhhCkpWSlRJVmtNdVpFZHYzeVYzV0FCR1lRSWNDSm1jSk5HeDJPZ0d4aEl1bVA5akdKK29ObXpKei9QQnJTNml4WFYKMjI0ZXg4Z2RhaDlLdlhCOWJ4YWg2OER0Rm1Xcwo=
