

- name: Download the AWS IAM Authenticator
  get_url:
    url: https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/darwin/amd64/aws-iam-authenticator
    dest: /usr/local/bin/aws-iam-authenticator
    mode: 0555
