apiVersion: v1
kind: ConfigMap
metadata:
  name: pax-operator-env
  namespace: pax-operator
data:
  MONGO-REPLICA-COUNT: "1"
  K8S_CLUSTER_NAME: $(CLUSTER-NAME)
  MONGO_AUTHENTICATION_DATABASE: admin
  MONGO_HOSTS: "mongo-deployment-0.mongo.mongo"
  MONGO_PASSWORD: admin
  MONGO_USERNAME: admin
  SHORTEN_PAX_HOSTNAME_COMPARE_VALUE: ""
  SPARK_DRIVER_CORES: "1"
  SPARK_DRIVER_MEMORY: 1g
  SPARK_EXECUTOR_CORES: "1"
  SPARK_EXECUTOR_MEMORY: 1g
