---

- name: Add the HTTP Subs library to the nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: 'load_module modules/ngx_http_subs_filter_module.so;'
    backup: yes

- name: Prevent compressed responses from proxied servers
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: "http {"
    line: 'proxy_set_header Accept-Encoding "";'
    backup: yes

- name: Prevent compressed responses from proxied servers
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertafter: "http {"
    backup: yes
    block: |
      #Prevent compressed responses from proxied servers
      proxy_set_header Accept-Encoding "";

      #Dynamic URLs require an explicit resolver
      resolver 10.0.0.2;

      #Disable compression to allow the plugin to work
      gzip off;


- name: Copy the nginx config
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    backup: yes
