#!/bin/bash
# paxata-server daemon
# chkconfig: 345 20 80
# description: paxata-server daemon
# processname: paxata-server.sh

DAEMON_PATH="/usr/local/paxata/server"
DAEMON=paxata-server.sh
DAEMONOPTS=""

NAME=paxata-server
DESC="Paxata Server"
SCRIPTNAME=/etc/init.d/$NAME

PAX_USER=paxata
PAX_GROUP=paxata
CURRENT_USER=`whoami`

case "$1" in
start)
    if [ "$CURRENT_USER" = "$PAX_USER" ]
    then
      $DAEMON_PATH/$DAEMON start $DAEMONOPTS
    else
      runuser -l $PAX_USER -c "$DAEMON_PATH/$DAEMON start $DAEMONOPTS"
    fi
;;
status)
    if [ "$CURRENT_USER" = "$PAX_USER" ]
    then
      $DAEMON_PATH/$DAEMON status
    else
      runuser -l $PAX_USER -c "$DAEMON_PATH/$DAEMON status"
    fi
;;
stop)
    if [ "$CURRENT_USER" = "$PAX_USER" ]
    then
      $DAEMON_PATH/$DAEMON stop
    else
      runuser -l $PAX_USER -c "$DAEMON_PATH/$DAEMON stop"
    fi
;;
restart)
    $0 stop
    $0 start
;;
*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
