---

- name: Create a tmp sub dir to make cleanup easy
  file:
    path: /tmp/secrets
    state: directory
    mode: 0755

- name: Get Digicert Secret from S3
  aws_s3:
    bucket: paxata-secrets
    object: digicert-secret
    dest: /tmp/secrets/digicert-secret
    mode: get


- name: Get the SSL Keys from the Private Github Vault
  git:
    repo: 'git@git-ansible-repo:Paxata/ansible.git'
    dest: /tmp/secrets/git/
    depth: 1
    accept_hostkey: yes


- name: Decrypt the Dev SSL Private Key
  command: ansible-vault decrypt --vault-password-file /tmp/secrets/digicert-secret /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxatadev_com.key

- name: Decrypt the Paxata Ninja Private Key
  command: ansible-vault decrypt --vault-password-file /tmp/secrets/digicert-secret /tmp/secrets/git/vault/certs/digicert/certs/star_paxata_ninja.key

- name: Decrypt the Prod SSL Private Key
  command: ansible-vault decrypt --vault-password-file /tmp/secrets/digicert-secret /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxata_com.key

- name: Copy the Paxata Ninja SSL Key to paxata dir
  copy:
    src: /tmp/secrets/git/vault/certs/digicert/certs/star_paxata_ninja.key
    dest: /usr/local/paxata/ssl-cert/star.paxata.ninja.key
    remote_src: yes
    mode: 0444
    backup: true

- name: Copy the dev SSL Key to paxata dir
  copy:
    src: /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxatadev_com.key
    dest: /usr/local/paxata/ssl-cert/star.paxatadev.com.key
    remote_src: yes
    mode: 0444
    backup: true

- name: Copy the Production SSL Key to paxata dir
  copy:
    src: /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxata_com.key
    dest: /usr/local/paxata/ssl-cert/star.paxata.com.key
    remote_src: yes
    mode: 0444
    backup: true

- name: Append a chain to paxata ninja cert
  shell: cat /tmp/secrets/git/vault/certs/digicert/certs/DigiCertCA.crt >> /tmp/secrets/git/vault/certs/digicert/certs/star_paxata_ninja.crt

- name: Append a chain to paxata ninja cert
  shell: cat /tmp/secrets/git/vault/certs/digicert/certs/DigiCertGlobalRootCA.crt >> /tmp/secrets/git/vault/certs/digicert/certs/star_paxata_ninja.crt

- name: Append a chain to dev cert
  shell: cat /tmp/secrets/git/vault/certs/digicert/certs/DigiCertCA.crt >> /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxatadev_com.crt

- name: Append a chain to dev cert
  shell: cat /tmp/secrets/git/vault/certs/digicert/certs/DigiCertGlobalRootCA.crt >> /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxatadev_com.crt

- name: Append a chain to prod cert
  shell: cat /tmp/secrets/git/vault/certs/digicert/certs/DigiCertCA.crt >> /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxata_com.crt

- name: Append a chain to prod cert
  shell: cat /tmp/secrets/git/vault/certs/digicert/certs/DigiCertGlobalRootCA.crt >> /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxata_com.crt

- name: Copy the Paxata Ninja SSL Cert to paxata dir
  copy:
    src: /tmp/secrets/git/vault/certs/digicert/certs/star_paxata_ninja.crt
    dest: /usr/local/paxata/ssl-cert/star.paxata.ninja.crt
    remote_src: yes
    mode: 0444
    backup: true

- name: Copy the dev SSL Cert to paxata dir
  copy:
    src: /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxatadev_com.crt
    dest: /usr/local/paxata/ssl-cert/star.paxatadev.com.crt
    remote_src: yes
    mode: 0444
    backup: true

- name: Copy the Production SSL Cert to paxata dir
  copy:
    src: /tmp/secrets/git/vault/certs/digicert/certs/digicert_star_paxata_com.crt
    dest: /usr/local/paxata/ssl-cert/star.paxata.com.crt
    remote_src: yes
    mode: 0444
    backup: true

- name: Delete the secrets directory
  file:
    path: /tmp/secrets
    state: absent
