---


- name: Update the file limits for root and all users
  blockinfile:
    path: "/etc/security/limits.conf"
    marker: "# {mark} File Limits"
    block: |
      *         hard    nofile      500000
      *         soft    nofile      500000
      root      hard    nofile      500000
      root      soft    nofile      500000
