apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

###
### The namespace is automatically added
### A Name Prefix is also automtically added
### The 'Tag Map' is synamically added as commonAnnotations

# Tell Kustomize to allow setting VARS using data  keys in ConfigMaps
configurations:
- varconfig.yaml

resources:
- ../kustomize/pax-installation/

patchesStrategicMerge:
# Apply the TShirt Size
- ../kustomize/sizing/pax-2.yaml


vars:
  - name: CLUSTER-NAME
    objref:
      kind: ConfigMap
      name: customer-configmap
      apiVersion: v1
    fieldref:
      fieldpath: data.CLUSTER-NAME
  - name: CUSTOMER-NAME
    objref:
      kind: ConfigMap
      name: customer-configmap
      apiVersion: v1
    fieldref:
      fieldpath: data.CUSTOMER-NAME
