
- name: Validate feature_source is set
  assert:
      that:
        - "feature_source != '' "
      msg: "feature_source, [s3 | url | teamcity ] is required"

- name: Install via S3
  import_tasks: install-pipeline-s3.yml
  when:
    - feature_source == "s3"

- name: Install via Flash
  import_tasks: install-pipeline-url.yml
  when:
    - feature_source == "url"

- name: Install via Team City
  import_tasks: install-via-teamcity.yml
  when:
    - feature_source == "teamcity"
