
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- varconfig.yaml

resources:
  - namespace.yaml
  - splunk-kubernetes-logging/
  - splunk-kubernetes-metrics/
  - splunk-kubernetes-objects/
namespace: splunk
configMapGenerator:
- name: splunk-properties
  literals:
  - SPLUNK-HEC-TOKEN=RDBEOEYzOTYtMThBMi00NkQ1LTk1NzctRUEzNDJDNzA2MTMy
  - SPLUNK-HEC-HOST=aW5wdXQtcHJkLXAtZHAyNmo0NzlubXhnLmNsb3VkLnNwbHVuay5jb20=
vars:
- name: SPLUNK-HEC-TOKEN
  objref:
    kind: ConfigMap
    name: splunk-properties
    apiVersion: v1
  fieldref:
    fieldpath: data.SPLUNK-HEC-TOKEN
- name: SPLUNK-HEC-HOST
  objref:
    kind: ConfigMap
    name: splunk-properties
    apiVersion: v1
  fieldref:
    fieldpath: data.SPLUNK-HEC-HOST
