version: '3.2'
services:
  devops-application:
    image: "devops-application:latest"
    volumes:
      - type: bind
        source: "${HOME}/.gitconfig"
        target: "/root/.gitconfig"
      - type: bind
        source: "${HOME}/.ssh"
        target: "/root/.ssh"
      - type: bind
        source: "${HOME}/.aws"
        target: "/root/.aws"
      - type: bind
        source: "${PROJECT_ROOT}"
        target: "/devops-application"
